### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by ddongule** [8th-caulion/JongwonyounIntroduce#5]
## 😉잘한 점 
- Bootstrap과 html tag들을 필요한 곳에 잘 배치해 홈페이지가 보기도 좋고, 사용하기에도 편합니다.
- 모든 CRUD가 잘 돌아갑니다!
- 선택 과제였던 댓글 기능을 완벽히 만드셨네요! 칭찬합니다👏👏👏
- 게시물을 작성하면 조회수가 얼마나 나오는지, 댓글이 얼마나 달렸는지 알 수 있게 표시도 해주셨어요.
- pythonanywhere을 이용해 배포를 시도해 보셨군요! 멋지게 배포된 사이트가 있다면 다음 수업에 친구들과 함께 공유해보셔도 좋을 것 같습니다!🤩

## 😎개선 사항(같이 배울 내용이 포함되어 있어요!)
- [x] 아마 Merge 할 때 생긴 것 같은데, Base.html에 `<<<<...` 등의 깃헙에서 써준 메시지들이 들어가있네요! 지워주시면 Nav Bar 뒤의 흐릿한 글자들이 사라지실거에요!
- [ ] Post할 때, 새 글 쓰기 버튼을 찾지 못해 /write 을 직접 치고 들어가야 하네요! 새 글 쓰기 버튼이 있으면 조금 더 편하게 글을 작성할 수 있을 것 같아요!
- [x] Nav Bar 영역의 쓰지 않으시는 부분은 지워주시는게 사용자의 입장에서 조금 더 보기 좋을 것 같아요!

## 🥳만드느라 수고하셨습니다! 같이 더 열심히 해봐용!

**Comment by korECM** [comment]
VSCode 상에서 Conflict를 해결했는데 메시지가 남아있는지는 몰랐네요ㅠ
Nav Bar는 원래 Search 기능까지 하려고 남겨놓은 거였는데 아무래도 시간이 없을 것 같아서 일단 지웠습니당!
글쓰기 버튼은 오른쪽 상단에 존재해요!

**Comment by ddongule** [comment]
오우 그렇군요 못봤어요!!!! 죄송해요~!!!!!!!!!!!
너무  잘 만들었습니당 멋져용!!!!!!! 😊
